checkoutLocation: leeway
workspaceLocation: leeway

image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 3000

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
- init: go get -v ./...
vscode:
  extensions:
    - zxh404.vscode-proto3@0.3.0:4f1jn72vQA2/LVoVSSmMtQ==