packages:
- name: dev-app
  type: go
  srcs:
  - "**/*.go"
  - go.mod
  - go.sum
  argdeps:
  - version
  config:
    buildArgs:
    - -ldflags
    - -X main.version=${version}
    library: false
- name: dev-init
  type: generic
  deps:
  - pkg/remotereporter:dev-init
  - pkg/ui:dev-init
- name: release
  type: generic
  srcs:
  - "**/*.go"
  - go.mod
  - go.sum
  - ".git/**"
  - ".goreleaser.yml"
  deps:
  - pkg/remotereporter:go-protocol
  config:
    commands:
    - ["cp", "pkg-remotereporter--go-protocol/go/protocol.pb.go", "pkg/remotereporter"]
    - ["curl", "-OL", "https://github.com/goreleaser/goreleaser/releases/download/v0.118.0/goreleaser_Linux_x86_64.tar.gz"]
    - ["tar", "xzf", "goreleaser_Linux_x86_64.tar.gz"]
    - ["./goreleaser"]