packages:
- name: go-protocol
  type: generic
  srcs:
  - protocol.proto
  config:
    commands:
    - ["go", "get", "-u", "github.com/golang/protobuf/protoc-gen-go"]
    - ["mkdir", "go"]
    - ["protoc", "-I=.", "--go_out=plugins=grpc:go", "protocol.proto"]
- name: dev-init
  type: generic
  deps:
  - :go-protocol
  config:
    commands:
    - ["cp", "pkg-remotereporter--go-protocol/go/protocol.pb.go", "${target}/pkg/remotereporter"]
- name: lots-of-output
  type: generic
  config:
    commands:
    - ["sh", "-c", "dd if=/dev/urandom bs=1k count=10 | base64"]